language: java
jdk: openjdk8
before_deploy:
  - mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
  - export project_version=$(mvn help:evaluate -N -Dexpression=project.version | grep -v '\[')
deploy:
  provider: releases
  api_key:
    secure: "NyZJeOT2NHVcHucurW70406cmDmy6wvPQYo5flgC5ug/tNtDV0X8YGrcBhWtVPTZemtssaSQefC4iflkdSE39J9uwomIsM8jLTsKFXMYQ+rsFZz20zawlkqJXl9TW12bmv6R2osHPVuULPFlK1u9XBGdKx+z8NFvVEgKiJH8hfgZud7ZEJZzUw6a6Soal7JfCcHeJl6QujgJDxbliFIB8L5QH1/3FZ2WNuly+nhVexEr2qhr1gZUO12WmcdIq9Et/BAGnH/pjK/mD5pIdy7hprQ7VPm6K0GUBnACaiHEsbEPrT0zD03J0JvSS4v0aBWaZqLUVT+oEniAoE6lEKMyXPxDR1g66iJM8vfg2FIEvWgcqSpNlUHULheXCEpFMwTKiU6PvrTXgQ2e0WESSfjgoMNVNv0qUY0WUXv62PV0mALI0VuzTEk+GD4oH6mxd0k0ev9vlnk2bPChbgy1WulI5J2t/d59EZ7PSdioI63JKgaQTTW3yuV6GdzFfAD4KMWeDEycIjaVa6SzKMKV60/cWnk0bgg7AbdCRgR4qiRT9IvGhhqIoXeRckz8N7N8fJB6TajpewWG+sYi+dFEeN5YiAs2L/mzdyrIdzy4XI1DWN4c7xc0X/3M8G76VrQaCAxMugmHKz4DbBTADQEujixfexc1DDlE9IpvIbI89A+ldqQ="
  file:
    - target/ebms-adapter-mule3-$project_version.zip
  skip_cleanup: true
  on:
    repo: java-ebms-adapter/ebms-adapter-mule3
    branch: master
  name: "$project_version"
addons:
  sonarcloud:
    organization: java-ebms-adapter
    token:
      secure: "WSML0zSdolH22dwKhqp0B4GwniDO9jTk19YGFDPnCsfi4Rue7pG+8pWIVwuPTybfaLLUOyX9zps1VpHoPw6fJ7lAuJ4Z/nVC664YmTYkayg1wZiQjJTqQOxlDzpfWGH9ovyVRXPr5a1SI5L1yfKk+WFF5xrBam/thydcViQbQn6XFhJFfxLiieDArZIjEsAXWHPB2KM91FeieOHb6zhzjJmGri5+k1yQyRkpa6A/lmNbOZKQZt3k5D9ntYhT4ug1rWREZUcCysqTpTrPuQxp0apTfjFe1IlAwyX6hixMH9cWPnOuzcCBWsERCjz1BerV9XAcmLtfF7cBAH7MUeM56i/x0FKQtdC+D3gndG+RF6h7B9IUjySs8WTjyFTGq0rn7OHrKZBj8Z+E7yvI6JynTJn9bJFutvoP97oAgfyxDYqQ7rJRTQ2hWJj5nUdt04jaGnvzNOksbv9Kv6sKpoURDOcVIOZgaLVzfY1wR0wMYh3qq3rSDBDpVXstm8Fmny7TEh+cwkQXKa5rOrmF7lmNhTuwDmz5Xj+ikZlfKclfLDuV5Su4obwU8wixpRBx1hgE+2DLt+w0l0qVkmwu5QqSu0D4McadR8lMsg9u6YM+5EweYHNAhCKleG8vSTlW8a6nUFtiv5pT8TAnDKGyPQJ2OydOV51gpwRaQcF4QKS3Qp8="
script:
  # The following command line builds the project, runs the tests with coverage and then executes the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=java-ebms-adapter_ebebms-adapter-mule3
