language: java
jdk: openjdk8
before_deploy:
  - mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
  - export project_version=$(mvn help:evaluate -N -Dexpression=project.version | grep -v '\[')
deploy:
  provider: releases
  api_key:
    secure: "BauYbtJZNbD4tAGWA3kZ5LnOn/0gCWfuTLCw+Na4RS+2QAugmABwFGqsOTfMHqs7Mgy8jniRQMvoYzZrdq2QtagC4jXUSXbht/gLyaL3cZ+6PXc5XuySKyzioglEEJxV0x0uNEKxJjVdgTLrt5jJwWKMR+RoDB0DWemjBDuWkdvP8izvk/xCxJGQxORvsRfnBXlGfyHse1KAskH2HN2weMcXNlUZUKHkKzKWI1uSHwQ1Yv3T++meVshbGFC4cnoYU6YS1UHh7Tp+W7xiiA2aTQpSlY3soerz67cBfE+wVZwqHSggDpEMewyrDzZwq6FHwqUk9/VeMxss1xbqZvUFxSp9q7Z81xsn20+3jA11+WBBNO9LytyM5beTe7j1YgwD9UBBcgAGdJmg8RwAmlG2XUNSTgaZA0TqONHuYakz87Mn668n7kTZzmrjGsPP596L1tnUkJxVsXYAkDVxPiaHI/JU3d9C7PcRZsUVmTAReU36hPfO0KWYtmxMZvZMAcz7wB+CPKAjVu2X7g47ZmMOLaX4HdOIw+yAc++zcxmQEl174tNyI46MFu3RpGIfhAhS4lr/VVZwS2hfHcxPilGFpNvaLlGHZyKf/JkKkwz/gihlKkDPq+1tQ/7KWKeaFv3K6P4sObSkvpxpmT5kwoerMQW/aXbmULMOQ6yw0YgoFO4="
  file:
    - target/ebms-adapter-mule3-$project_version.zip
  skip_cleanup: true
  on:
    repo: java-ebms-adapter/ebms-adapter-mule3
    branch: master
  name: "$project_version"
addons:
  sonarcloud:
    organization: java-ebms-adapter
    token:
      secure: "kw7Xdu3O4CGNtmMW7Ws/vJyzcpAlbZDNzBEY3QaQzp+PK+qHRsN0AU/7yF2Sc7w3UD66+SRShC4feLifQAlrinmOnrd+D+0hYrEI35it1gmtk9YS1A/SkWLXvzMbPv4T2zoD8K0TY+BE50YHNg0oXp4Gn6BQpyuI7/NJeQyb2d1uzbv74eit9IrRimRvn3Agieuvy11oCERodEuFir1UWej1RCuFlqdyzghRLFyaw2PGUiBj/FvEOsyVYjENZbo7cahScFIK5pc9Kd3AOWvctVGduqPso07CIWMuBa7y03lHxEKCPerdwz5Ky0MAJL+NGiSsJNZT6Kjz4K1deARO0oU7fDJvzwMf57ju5xdysm19bQBQgCop650I2pjHfwtRkSG3wYetE1ytXdyX3mknxUedcTq9IEwy8oklT5M65hAelX8yhdhEjhdBK3EnA6WAwDE2W943xH9v15y3gR9KEdzaTulb+Qj6tBhIyLm7qETkJsFa8doUhldDe8NuIfAvdJnHYicjcSRSyByo9+CHAMeZ5sqliNthptCS13r44sjPlckqv9QSbSO6ss4SrRlrURg3NY9ExcpFBcivxdKRYnRK3Prs9di+tRuaKvpXIPzDozSp7K565NBpJhSYJraGfci2hwKm6TlkXZagHuzeg3nvuUJhaMXgncEEga64YVw="
script:
  # The following command line builds the project, runs the tests with coverage and then executes the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=java-ebms-adapter_ebebms-adapter-mule3
