language: java
jdk: openjdk8
before_deploy:
  - mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
  - export project_version=$(mvn help:evaluate -N -Dexpression=project.version | grep -v '\[')
deploy:
  provider: releases
  api_key:
    secure: "NyZJeOT2NHVcHucurW70406cmDmy6wvPQYo5flgC5ug/tNtDV0X8YGrcBhWtVPTZemtssaSQefC4iflkdSE39J9uwomIsM8jLTsKFXMYQ+rsFZz20zawlkqJXl9TW12bmv6R2osHPVuULPFlK1u9XBGdKx+z8NFvVEgKiJH8hfgZud7ZEJZzUw6a6Soal7JfCcHeJl6QujgJDxbliFIB8L5QH1/3FZ2WNuly+nhVexEr2qhr1gZUO12WmcdIq9Et/BAGnH/pjK/mD5pIdy7hprQ7VPm6K0GUBnACaiHEsbEPrT0zD03J0JvSS4v0aBWaZqLUVT+oEniAoE6lEKMyXPxDR1g66iJM8vfg2FIEvWgcqSpNlUHULheXCEpFMwTKiU6PvrTXgQ2e0WESSfjgoMNVNv0qUY0WUXv62PV0mALI0VuzTEk+GD4oH6mxd0k0ev9vlnk2bPChbgy1WulI5J2t/d59EZ7PSdioI63JKgaQTTW3yuV6GdzFfAD4KMWeDEycIjaVa6SzKMKV60/cWnk0bgg7AbdCRgR4qiRT9IvGhhqIoXeRckz8N7N8fJB6TajpewWG+sYi+dFEeN5YiAs2L/mzdyrIdzy4XI1DWN4c7xc0X/3M8G76VrQaCAxMugmHKz4DbBTADQEujixfexc1DDlE9IpvIbI89A+ldqQ="
  file:
    - target/ebms-adapter-mule3-$project_version.zip
  skip_cleanup: true
  on:
    repo: java-ebms-adapter/ebms-adapter-mule3
    branch: master
  name: "$project_version"
addons:
  sonarcloud:
    organization: java-ebms-adapter
    token:
      secure: "b3qSfYD7HudZEZhWfECi7VqJ18LLea5ZY/tCrLx6HpyfG02nTccRvfBNZEwUuLjAVBb/zpyvGe7wUreDTjtIwglBBSfcYorfzHzHMD3jkghDtSTt5ya5dTcTudJK7bpwjssF74O4flcYKbBsLzlfwuizjP/J98jJ/9W7OVbCDuhC0Ukq/mS1mZDxLH8oQwRHXy9fUN6nw39IoaxrWp5LMgaSTb3YQ8/iU1ASZqxAdzun7IlTb7kgzTYnCGkDqaqfCmPmDqi3htSHO7V2HgmmZOOHQDphGnfiQpTxhi1QUvP64GT+n+hkGrnQKVssutmJ20FsiG7SH46KTqJDzTqh1r6M8RIX1OjNUqStemDznNE98r7QakPwmicftIY3sDwEosVtA+WgcyfC4TsbEvfsneai02z8Jkd2aL3j/oAG6522p+XqHiSy30XMsxuev1iUGxRaaO+5Kn9vJ2V0sboKxzyMk/51ibvAHs3/hVobDZchwRiv126ooX4ys/SH/2K8x2IEvADuYPlm9nFaioAmtg/qqvlb3F4qSB3sQ43/23ckyLkVjBRFsXtTGQ2ZogWjml5QZaqRjVS2liJay9Xav1VjWCxGrmni+sAdM/zpKzHZpZVLIvo4pce9wWK/4wMYfd01lJIe4XQexeRGuh4uirA9HwaKsU6UBYhuXNVR+WA="
script:
  # The following command line builds the project, runs the tests with coverage and then executes the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=java-ebms-adapter_ebms-adapter-mule3
